# Csound build options for Linux
set(BUILD_CSBEATS ON)
set(BUILD_CXX_INTERFACE ON)
set(BUILD_DSSI_OPCODES OFF)
set(BUILD_INSTALLER ON)
set(BUILD_JAVA_INTERFACE ON)
set(BUILD_LUA_INTERFACE OFF)
set(BUILD_MULTI_CORE ON)
set(BUILD_PADSYNTH_OPCODES ON)
set(BUILD_RELEASE ON)
set(BUILD_SCANSYN_OPCODES ON)
set(BUILD_STATIC_LIBRARY ON)
set(BUILD_TESTS ON)
set(BUILD_UTILITIES ON)

# Csound use features
set(USE_ALSA ON)
set(USE_ATOMIC_BUILTIN ON)
set(USE_AUDIOUNIT 0) # N/A
set(USE_CURL ON)
set(USE_COMPILER_OPTIMIZATIONS ON)
set(USE_COREMIDI 0) # N/A
set(USE_DOUBLE ON)
set(USE_GETTEXT	ON)
set(USE_IPMIDI ON)
set(USE_JACK ON)
set(USE_LIB64 ON)
set(USE_LRINT ON)
set(USE_PORTAUDIO ON)
set(USE_PORTMIDI ON)
set(USE_PULSEAUDIO ON)
set(USE_SYSTEM_PORTSMF ON)

# Misc build options
set(HAVE_BIG_ENDIAN 0)
set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_16BIT_TYPE "unsigned short")
set(FAIL_MISSING OFF) # Enable when packaging
